### ISSUE TITLE
Error while trying to push

### ISSUE THREAD

**Issue by checktor** [rkleee/aragonit#1]
error message:

remote: error: GH007: Your push would publish a private email address.
remote: You can make your email public or disable this protection by visiting:
remote: http://github.com/settings/emails
To git@github.com:rkleee/aragonit.git
 ! [remote rejected] master -> master (push declined due to email privacy restrictions)
error: Fehler beim Versenden einiger Referenzen nach 'git@github.com:rkleee/aragonit.git'

**Comment by rkleee** [comment]
Ich würde sagen, das ist jetzt ein leicht anderer Fehler... zuerst wurde doch bemängelt, dass die Private Settings nicht aktiviert wären, oder?

**Comment by rkleee** [comment]
Dann habe ich das ausgewählt, weil das den vorherige Fehler beheben sollte:
" Keep my email address private

We'll remove your public profile email and use rkleee@users.noreply.github.com when performing web-based Git operations and sending email on your behalf. If you want command line Git operations to use your private email you must set your email in Git. "

Und jetzt scheint diese Option das Problem zu sein.

**Comment by rkleee** [comment]
Wäre es denkbar, dass sich das vielleicht auf deine EMail-Einstellungen bezieht? Der an dich gerichtete Hinweis sagt dir, dass du deine Maileinstellungen anpassen sollst.

**Comment by checktor** [comment]
Ok, jetzt läuft's.
Das Problem war, dass ich bei mir lokal einen Commit gemacht hatte und da noch meine alte (richtige) E-Mail-Adresse stand. Habs neu geclont und mit der GutHub-Mail commited und jetzt läufts.

**Comment by cokron** [comment]
Ich hatte den gleichen Fehler. Grund war so einfach wie doof - trotz jahrelanger Erfahrung mit git:
ich hatte lokal noch keinen Commit gemacht und hatte versucht, zu pushen. Das geht offensichtlich nicht, wenn das Repo lokal und remote noch keinen einzigen Commit hat. Fehlermeldung war die gleiche!
